ATGScrape/ATGScrape/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import include
from scrapeApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.BasePage,name='basepage'),
    url(r'^Scraper/',include('scrapeApp.urls')),
]

ATGScrape/scrapeApp/urls.py
from django.conf.urls import url
from scrapeApp import views

app_name = 'scrapeApp'

urlpatterns = [

    url(r'^$',views.InputURLPage,name='inputurlpage'),
    url(r'^CheckURLPage/$',views.CheckURLPage,name='checkurlpage'),
    url(r'^InsiderData/$',views.DataPage,name='datapage'),
    url(r'^ScrapeEvent/$',views.EventsHighURLPage,name='eventhighurlpage'),
    url(r'^CheckEventURLPage/$',views.CheckEventURLPage,name='checkeventurlpage'),
    url(r'^EventHighData/$',views.EventsHighDataPage,name='eventhighdatapage'),
    url(r'^ScrapeYoga/$',views.NaadYogaURLPage,name='naadyogaurlpage'),
    url(r'^CheckYogaURLPage/$',views.CheckYogaURLPage,name='checkyogaurlpage'),
    url(r'^NaadYogaDataPage/$',views.NaadYogaDataPage,name='naadyogadatapage'),
    url(r'^AddToNonPage/$',views.AddToNonPage,name='addtononpage'),
    url(r'^ViewUrlsPage/$',views.ViewURLsPage,name='viewurlspage')


]

ATGScrape/scrapeApp/models.py
from django.db import models

# Create your models here.
class EventModel(models.Model):

    event_name = models.CharField(max_length=300)
    event_date = models.CharField(max_length=300)
    event_price = models.CharField(max_length=30)
    event_venue = models.CharField(max_length=300)
    event_category = models.CharField(max_length=300)

    def __str__(self):

        return self.event_name

class YogaModel(models.Model):

    name = models.CharField(max_length=264)
    postcode = models.CharField(max_length=264)
    qualification = models.CharField(max_length=264)
    vision = models.TextField()
    link = models.URLField()

    def __str__(self):

        return self.name

class HighModel(models.Model):

    event_name = models.CharField(max_length=264)
    location = models.CharField(max_length=365)
    date = models.CharField(max_length=254)
    category = models.CharField(max_length=243)

    def __str__(self):

        return self.event_name


class InterestingURLModel(models.Model):

    interesting_url = models.URLField()

    def __str__(self):

        return self.interesting_url

class NotInterestingURLModel(models.Model):

    not_interesting_url = models.URLField()

    def __str__(self):

        return self.not_interesting_url

ATGScrape/scrapeApp/views.py
from django.shortcuts import render
import pandas as pd
from scrapeApp.models import EventModel
import operator
from bs4 import BeautifulSoup
import requests
import csv
from scrapeApp.models import InterestingURLModel,NotInterestingURLModel
from scrapeApp.models import YogaModel,HighModel
# Create your views here.
def BasePage(request):

    return render(request,'scrapeApp/BasePage.html')

def InputURLPage(request):

    return render(request,'scrapeApp/InputURLPage.html')

def DataPage(request):

    events = EventModel.objects.order_by('event_name')
    ordered = sorted(events, key=operator.attrgetter('event_name'))
    flag = True


    if request.method == 'POST':

        url = request.POST.get('url')

        data = InterestingURLModel.objects.create(interesting_url = url)
        data.save()

        url_li = url.split('/')
        category = ''.join(url_li[len(url_li)-1])

        html_text = requests.get(url).text
        soup = BeautifulSoup(html_text, 'lxml')
        events = soup.findAll('div', class_ = 'event-card-details-top')
        price = soup.findAll('div', class_ = 'event-card-container')

        for e,p in zip(events,price):

            name= e.find('span', class_ = 'event-card-name-string').text
            date = e.find('span', class_ = 'event-card-date').text
            price = p.find('div', class_ = 'event-card-price').text
            venue = e.find('span', class_ = 'event-card-venue').text


            if EventModel.objects.count() == 0:
                events = EventModel.objects.create(event_name = name, event_date = date, event_price = price, event_venue = venue, event_category = category)
                events.save()

            else:
                names = EventModel.objects.all().values()
                names = list(names)
                temp = []

                for i in range(len(names)):
                    temp.append(names[i]['event_name'])
                if name not in temp:
                    flag =False
                    events = EventModel.objects.create(event_name = name, event_date = date, event_price = price, event_venue = venue, event_category = category)
                    events.save()


    if flag == False:

        events = EventModel.objects.order_by('event_name')
        ordered = sorted(events, key=operator.attrgetter('event_name'))
        file = open('insider_event.csv', 'w', encoding='utf-8')
        writer = csv.writer(file)

        writer.writerow(['EVENT NAME','EVENT DATE & TIME','EVENT PRICE','EVENT VENUE','EVENT CATEGORY'])

        for item in ordered:
            writer.writerow([item.event_name,item.event_date,item.event_price,item.event_venue,item.event_category])
        file.close()

        df = pd.read_csv('insider_event.csv', encoding='utf-8')

        df.to_excel('insider_event.xlsx', index = False, encoding='utf-8')

    return render(request,'scrapeApp/DataPage.html',{'events':ordered})


def CheckURLPage(request):

    if request.method == 'POST':

        url = request.POST.get('url')

    return render(request,'scrapeApp/CheckURLPage.html',{'url':url})

def CheckEventURLPage(request):

    if request.method == 'POST':

        url = request.POST.get('url')

    return render(request,'scrapeApp/CheckEventURLPage.html',{'url':url})

def AddToNonPage(request):

    if request.method == 'POST':

        take_url = request.POST.get('take_url')

        data = NotInterestingURLModel.objects.create(not_interesting_url = take_url)

        data.save()

    return render(request,'scrapeApp/AddToNonPage.html')



def EventsHighURLPage(request):

    return render(request,'scrapeApp/EventsHighURLPage.html')


def EventsHighDataPage(request):

    events = HighModel.objects.order_by('event_name')
    ordered = sorted(events, key=operator.attrgetter('event_name'))
    flag = True


    if request.method == 'POST':

        url = request.POST.get('url')

        data = InterestingURLModel.objects.create(interesting_url = url)
        data.save()



        html_text = requests.get(url).text
        soup = BeautifulSoup(html_text, 'lxml')

        event_names = soup.find_all('div', class_ = 'truncate f-s-16 f-s-sm-12 l-h-1p5 color-dark-grey')
        locations = soup.find_all('div', class_ = 'truncate f-s-16 f-s-sm-12 l-h-1p5 color-light-grey text-capitalize')
        dates = soup.find_all('div' , class_ = 'truncate f-s-16 f-s-sm-12 f-w-500 l-h-1p5 color-dark-grey')
        category = soup.find_all('a' , class_ = 'category-pill d-inline-block f-s-12 f-s-sm-8 f-w-sm-500 text-capitalize')


        for e,l,d,c in zip(event_names,locations,dates,category):

            name = e.text
            location = l.text
            date = d.text
            category = c.text

            if HighModel.objects.count() == 0:

                high = HighModel.objects.create(event_name = name, location = location, date = date, category = category)
                high.save()
            else:

                names = HighModel.objects.all().values()
                names = list(names)
                temp = []

                for i in range(len(names)):
                    temp.append(names[i]['event_name'])
                if name not in temp:
                    flag =False
                    high = HighModel.objects.create(event_name = name, location = location, date = date, category = category)
                    high.save()


    if flag == False:

        events = HighModel.objects.order_by('event_name')
        ordered = sorted(events, key=operator.attrgetter('event_name'))
        file = open('high_event.csv', 'w', encoding='utf-8')
        writer = csv.writer(file)

        writer.writerow(['EVENT NAME','LOCATION','DATE','CATEGORY',])

        for item in ordered:
            writer.writerow([item.event_name,item.location,item.date,item.category])
        file.close()

        df = pd.read_csv('high_event.csv', encoding='utf-8')

        df.to_excel('high_event.xlsx', index = False, encoding='utf-8')


    return render(request,'scrapeApp/EventsHighDataPage.html',{'events':ordered})


def NaadYogaURLPage(request):

    return render(request,'scrapeApp/NaadYogaURLPage.html')

def CheckYogaURLPage(request):

    if request.method == 'POST':

        url = request.POST.get('url')

    return render(request,'scrapeApp/CheckYogaURLPage.html',{'url':url})


def NaadYogaDataPage(request):

    yoga = YogaModel.objects.order_by('name')
    ordered = sorted(yoga, key=operator.attrgetter('name'))
    flag=True

    if request.method == 'POST':

        url = request.POST.get('url')

        data = InterestingURLModel.objects.create(interesting_url = url)
        data.save()



        html_text = requests.get(url).text
        soup = BeautifulSoup(html_text, 'lxml')

        names = soup.findAll('td', class_ = 'column-1')
        postcode = soup.findAll('td', class_ = 'column-3')
        qualification = soup.findAll('td', class_ = 'column-4')
        vision = soup.findAll('td', class_ = 'column-5')
        link = soup.findAll('td', class_ = 'column-6')

        for e,p,q,v,l in zip(names,postcode,qualification,vision,link):

            name = e.text
            postcode = p.text
            qualification = q.text
            vision = v.text
            link = l.text

            if YogaModel.objects.count == 0:

                yoga = YogaModel.objects.create(name = name, postcode = postcode, qualification = qualification, vision = vision, link = link)
                yoga.save()

            else:
                names = YogaModel.objects.all().values()
                names = list(names)
                temp = []

                for i in range(len(names)):
                    temp.append(names[i]['name'])

                if name not in temp:
                    flag =False
                    yoga = YogaModel.objects.create(name = name, postcode = postcode, qualification = qualification, vision = vision, link = link)
                    yoga.save()


    if flag == False:

        yoga = YogaModel.objects.order_by('name')
        ordered = sorted(yoga, key=operator.attrgetter('name'))
        yoga_file = open('yoga_event.csv', 'w', encoding='utf-8')
        writer = csv.writer(yoga_file)

        writer.writerow(['INSTRUCTOR NAME','POSTCODE','QUALIFICATION','VISION','LINK'])

        for item in ordered:
            writer.writerow([item.name,item.postcode,item.qualification,item.vision,item.link])

        yoga_file.close()

        df = pd.read_csv('yoga_event.csv', encoding='utf-8')

        df.to_excel('yoga_event.xlsx', index = False, encoding='utf-8')


    return render(request,'scrapeApp/NaadYogaDataPage.html',{'yoga':ordered})

def ViewURLsPage(request):

    int_url = InterestingURLModel.objects.all()
    not_int = NotInterestingURLModel.objects.all()

    return render(request,'scrapeApp/ViewURLsPage.html',{'int':int_url,'not':not_int})

ATGScrape/scrapeApp/templates/scrapeApp/AddToNonPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}


{% block bodyblock %}

  <h5>Added to Not Interesting URLs...</h5>


{% endblock %}

ATGScrape/scrapeApp/templates/scrapeApp/BasePage.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>

    <div class="container">
      <div class="jumbotron">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'basepage' %}">ATG Scrapper</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'scrapeApp:inputurlpage' %}">Scrape insider.in</a>
          </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'scrapeApp:eventhighurlpage' %}"> Scrape eventshigh.com </a>
          </li>

          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'scrapeApp:naadyogaurlpage' %}"> Scrape naadyogacouncil.com </a>
          </li>

          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'scrapeApp:viewurlspage' %}">View Interesting and Not Interesting Urls Table</a>
          </li>

          </ul>

          </div>
          </div>
          </nav>



        {% block bodyblock %}

          <div class="container" style=" text-align: center; " >
              <h2>ATG Web-Scraper Task 3</h2><br><br>
            <h5 style=" font-style: italic; " >
                <strong>
                  Welcome to the ATG Web Scrapper Task Solution <br><br> The task consists of specified websites
                  from which we are supposed to scrape the structured data. The urls from which we could scrape
                  are stored in interesting table of urls and the urls that do not possess any kind of structured data
                  are stored in not interesting urls tables.
                  <br><br>
                  Please Follow the links above to follow the tasks.

                </strong>
            </h5>
          </div>
        {% endblock %}
      </div>
    </div>


  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>




  </body>
</html>

ATGScrape/scrapeApp/templates/scrapeApp/CheckEventURLPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}




{% block bodyblock %}

<form  action="{% url 'scrapeApp:eventhighdatapage' %}" method="post">
  {% csrf_token %}
  <br><br>
  <h5 style=" text-align: center; " >Contents of {{ url }}:</h5>
  <input type="hidden" name="url" value="{{ url }}">
    <iframe src="{{ url }}" width="1000" height="400" style=" border-color: black; "  >
    </iframe>
    <br><br>
    <input style=" position: relative; top:50%; left:30%; " type="submit" name="" class="btn btn-info" value="Add to Interesting URLS Table & Scrape the website">

</form>
<br>
<form action="{% url 'scrapeApp:addtononpage' %}"  method="post">
  {% csrf_token %}

  <input type="hidden" name="take_url" value="{{ url }}">
  <input type="submit" name="" class="btn btn-outline-danger" value="Add To Not Intersting URLs">
</form>






{% endblock %}

ATGScrape/scrapeApp/templates/scrapeApp/CheckURLPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}

{% block bodyblock %}

<form  action="{% url 'scrapeApp:datapage' %}" method="post">
  {% csrf_token %}
  <br><br>
  <h5 style=" text-align: center; " >Contents of {{ url }}:</h5>
  <input type="hidden" name="url" value="{{ url }}">
    <iframe src="{{ url }}" width="1000" height="400" style=" border-color: black; "  >
    </iframe>
    <br><br>
    <input style=" position: relative; top:50%; left:30%; " type="submit" class="btn btn-info" name="" value="Add to Interesting URLS Table & Scrape the website">

</form>
<br>
<form action="{% url 'scrapeApp:addtononpage' %}"  method="post">
  {% csrf_token %}

  <input type="hidden" name="take_url" value="{{ url }}">
  <input type="submit" name="" class="btn btn-outline-danger" value="Add To Not Intersting URLs">
</form>


{% endblock %}

ATGScrape/scrapeApp/templates/scrapeApp/CheckYogaURLPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}

{% block bodyblock %}

<form  action="{% url 'scrapeApp:naadyogadatapage' %}" method="post">
  {% csrf_token %}
  <br><br>
  <h5 style=" text-align: center; " >Contents of {{ url }}:</h5>
  <input type="hidden" name="url" value="{{ url }}">
    <iframe src="{{ url }}" width="1000" height="400" style=" border-color: black; "  >
    </iframe>
    <br><br>
    <input style=" position: relative; top:50%; left:30%; " type="submit" class="btn btn-info" name="" value="Add to Interesting URLS Table & Scrape the website">

</form>
<br>
<form action="{% url 'scrapeApp:addtononpage' %}"  method="post">
  {% csrf_token %}

  <input type="hidden" name="take_url" value="{{ url }}">
  <input type="submit" name="" class="btn btn-outline-danger" value="Add To Not Intersting URLs">
</form>


{% endblock %}

ATGScrape/scrapeApp/templates/scrapeApp/DataPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}


{% block bodyblock %}
  <h2> <strong> Data Stored in Local Model </strong> </h2>


    <div class="container">
        {% for e in events %}
        <div class="row">
          <div class="col-sm">
            <ul class="list-group">
            <li class="list-group-item">{{ e.event_name }}</li>
            <li class="list-group-item"> {{ e.event_date }}</li>
            <li class="list-group-item">{{ e.event_price }}</li>
            <li class="list-group-item"> {{ e.event_venue }}</li>
            <br>
            </ul>
          </div>
        </div>
    {% endfor %}
  </div>





{% endblock %}

ATGScrape/scrapeApp/templates/scrapeApp/EventsHighDataPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}


{% block bodyblock %}
<h2>Data Stored in Local Model</h2>

<div class="container">
    {% for e in events %}
    <div class="row">
      <div class="col-sm">
        <ul class="list-group">
        <li class="list-group-item">{{ e.name }}</li>
        <li class="list-group-item"> {{ e.location }}</li>
        <li class="list-group-item">{{ e.date }}</li>
        <li class="list-group-item"> {{ e.category }}</li>
        <br>
        </ul>
      </div>
    </div>
{% endfor %}
</div>



{% endblock %}

ATGScrape/scrapeApp/templates/scrapeApp/EventsHighURLPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}

{% block bodyblock %}

  <h2>Input urls from events high:</h2><br>

  <form action="{% url 'scrapeApp:checkeventurlpage' %}" method="post" style=" text-align:  center; " >
    {% csrf_token %}
      <input type="text" name="url" style=" width: 400px; " placeholder="Enter Websites url here!!"><br><br>

      <input type="submit" name="" class="btn btn-warning" value="Load">

  </form>




{% endblock %}

ATGScrape/scrapeApp/templates/scrapeApp/InputURLPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}

{% block bodyblock %}

  <h2>Input urls from insider's web page:</h2><br>

  <form action="{% url 'scrapeApp:checkurlpage' %}" method="post" style=" text-align:  center; " >
    {% csrf_token %}
      <input type="text" name="url" style=" width: 400px; " placeholder="Enter Websites url here!"><br><br>

      <input type="submit" name="" class="btn btn-warning"  value="Load">

  </form>



{% endblock %}

ATGScrape/scrapeApp/templates/scrapeApp/NaadYogaDataPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}


{% block bodyblock %}
<h2>Data Stored in Local Model</h2>

<div class="container">
    {% for e in yoga %}
    <div class="row">
      <div class="col-sm">
        <ul class="list-group">
        <li class="list-group-item">{{ e.name }}</li>
        <li class="list-group-item"> {{ e.postcode }}</li>
        <li class="list-group-item">{{ e.qualification }}</li>
        <li class="list-group-item"> {{ e.vision }}</li>
        <li class="list-group-item"> {{ e.link }}</li><br>
        </ul>
      </div>
    </div>
{% endfor %}
</div>



{% endblock %}

ATGScrape/scrapeApp/templates/scrapeApp/NaadYogaURLPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}

{% block bodyblock %}

  <h2> Input urls from naadyoga webpage:</h2><br>

  <form action="{% url 'scrapeApp:checkyogaurlpage' %}" method="POST" style=" text-align:  center; " >
    {% csrf_token %}
      <input type="text" name="url" style=" width: 400px; " placeholder="Enter Websites url here!"><br><br>

      <input type="submit" name="" class="btn btn-warning" value="Load">

  </form>




{% endblock %}

ATGScrape/scrapeApp/templates/scrapeApp/ViewURLsPage.html
<!DOCTYPE html>
{% extends 'scrapeApp/BasePage.html' %}


{% block bodyblock %}

  <div class="container">
  <div class="row">
  <div class="col-sm">
    Interesting URLS:
    <ul class="list-group">
      {% for i in int %}
      <li class="list-group-item"> <a href="{{i}}" target="_blank" >{{ i }}</a></li>
      {% endfor %}
    </ul>

  </div>
  <div class="col-sm">
    Not Interesting URLS:
    <ul class="list-group">
      {% for i in not %}
      <li class="list-group-item"> <a href="{{i}}" target="_blank" >{{ i }}</a></li>
      {% endfor %}
    </ul>

  </div>

  </div>
  </div>


{% endblock %}